routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth Routes
Auth::routes();

// Basic Routes
//Route::get('/home', 'HomeController@index');

Route::post('login', 'Auth\LoginController@postLogin');
Route::post('register', 'Auth\RegisterController@register');



// Protected Routes
Route::group(['middleware' => 'auth'], function () {

    Route::view('/', 'app.index')->name('dashboard');
    Route::get('/offers', 'OfferController@Index')->name('affiliate.offers');
    Route::view('/offers/mine', 'app.offers.mine')->name('affiliate.offers.mine');
    Route::get('/offers/{id}','OfferController@show')->name('affiliate.offers.show');
    Route::view('/report','app.report.index')->name('affiliate.report');
    Route::view('/billing','app.billing.billing')->name('billing');

//    Route::get('/', 'ExampleController@getIndexExample');
    Route::get('blank-example', 'ExampleController@getBlankExample');
    Route::get('desktop-example', 'ExampleController@getDesktopExample');

    Route::get('users', 'UserController@getUserList');

});

// Image Routes
// @WARNING: The 'image' prefix is reserved for SomelineImageService
Route::group(['prefix' => 'image'], function () {

    Route::group(['middleware' => 'auth'], function () {
        Route::post('/', 'ImageController@postImage');
    });

    Route::get('{type}/{name}', 'ImageController@showTypeImage');
    Route::get('/{name}', 'ImageController@showOriginalImage');

});

// Locale Routes
// @WARNING: The 'locales' prefix is reserved for SomelineLocaleController
Route::group(['prefix' => 'locales'], function () {

    Route::get('/{locale}.js', '\Someline\Support\Controllers\LocaleController@getLocaleJs');

    Route::get('/switch/{locale}', '\Someline\Support\Controllers\LocaleController@getSwitchLocale');

});

app/Models/BaseModel.php
<?php
/**
 * Created for someline-starter.
 * User: Libern
 */

namespace Someline\Models;

use Someline\Base\Models\BaseModel as Model;
use Someline\Models\Foundation\User;

class BaseModel extends Model
{

    /**
     * @return User|null
     */
    public function getUser()
    {
        return parent::getUser();
    }

    /**
     * @return User|null
     */
    public function getAuthUser()
    {
        return parent::getAuthUser();
    }

    /**
     * @return User|null
     */
    public function getRelatedUser()
    {
        return $this->related_user;
    }


}

resources/views/app/layout/parts/aside.blade.php
<!-- aside -->
<aside id="aside" class="app-aside hidden-xs bg-black">
    <div class="aside-wrap">
        <div class="navi-wrap">
{{--            @include('app.layout.parts.aside.user')--}}

            @include('app.layout.parts.aside.nav')

{{--            @include('app.layout.parts.aside.footer')--}}
        </div>
    </div>
</aside>
<!-- / aside -->

resources/views/app/layout/parts/content.blade.php
<!-- content -->
<div id="content" class="app-content" role="main" style="padding-bottom: 100px">

    @yield('content')

</div>
<!-- /content -->

resources/views/app/layout/parts/footer.blade.php
<!-- footer -->
<footer id="footer" class="app-footer" role="footer">
    <div class="wrapper b-t bg-light">
        <span class="pull-right"> <a href ui-scroll="app" class="m-l-sm text-muted"><i class="fa fa-long-arrow-up"></i></a></span>
        @include('app.layout.parts.footer.copyright')
    </div>
</footer>
<!-- / footer -->

resources/views/app/layout/parts/footer_desktop.blade.php
<!-- footer -->
<footer id="footer" class="app-footer" role="footer">
    <div class="wrapper b-t bg-light">
        <div class="app-desktop-wrapper">
            <span class="pull-right"> <a href ui-scroll="app" class="m-l-sm text-muted"><i
                            class="fa fa-long-arrow-up"></i></a></span>
            @include('app.layout.parts.footer.copyright')
        </div>
    </div>
</footer>
<!-- / footer -->

resources/views/app/layout/parts/header.blade.php
<!-- header -->
<header id="header" class="app-header navbar box-shadow" role="menu">
    @include('app.layout.parts.navbar.header')
    @include('app.layout.parts.navbar.collapse')
    <div ui-butterbar="" class="butterbar hide"><span class="bar"></span></div>
</header>
<!-- / header -->

resources/views/app/layout/parts/header_desktop.blade.php
<!-- header -->
<header id="header" class="app-header navbar box-shadow bg-primary" role="menu">
    <div class="app-desktop-wrapper">
        @include('app.layout.parts.navbar.header_without_aside')
        @include('app.layout.parts.navbar.collapse_without_aside')
    </div>
    <div ui-butterbar="" class="butterbar hide"><span class="bar"></span></div>
</header>
<!-- / header -->

resources/views/app/layout/parts/header_without_aside.blade.php
<!-- header -->
<header id="header" class="app-header navbar box-shadow" role="menu">
    @include('app.layout.parts.navbar.header_without_aside')
    @include('app.layout.parts.navbar.collapse_without_aside')
    <div ui-butterbar="" class="butterbar hide"><span class="bar"></span></div>
</header>
<!-- / header -->